// @generated
// This file was automatically generated and should not be edited.

import Apollo

public extension ShopifyAdminAPI.Objects {
  /// Comment events are generated by staff members of a shop.
  /// They are created when a staff member adds a comment to the timeline of an order, draft order, customer, or transfer.
  ///
  static let CommentEvent = Object(
    typename: "CommentEvent",
    implementedInterfaces: [
      ShopifyAdminAPI.Interfaces.Event.self,
      ShopifyAdminAPI.Interfaces.Node.self
    ]
  )
}